### ISSUE TITLE
Updates for SSL Requirement on Flickr

### ISSUE THREAD

**Issue by jimjam-slam** [ohookins/flickr-shell-uploader#1]
Hi there! Thanks very much for this script; I was struggling to understand the Flickr API process, and it really helped me figure out what was happening.

I found that I had to change a few things to comply with what seems liek changes in the API:
- I added `-s` to the `curl` statements to enable SSL connection
- I changed all the API URLs from `http` to `https`
- I changed the upload URL to `https://up.flickr.com/services/upload/`

I also found curl a bit slow, and although I'm still figuring out how best to optimise it (I'm also running a few other things on this computer, which is a Raspberry Pi, so it's possible I'm asking it to do too much), I found adding `-H "Expect:"` helped cut out a delay at the start, because curl's verbose output kept saying that it was done waiting for 100-continue after pausing for a while.

Thanks again!

**Comment by ohookins** [comment]
They sound like reasonable changes. Care to make a pull request for them and I merge it!

**Comment by ohookins** [comment]
I'm not going to update this repo anymore, feel free to fork and make any changes yourself as you wish.
