### ISSUE TITLE
Authentication broken?

### ISSUE THREAD

**Issue by jamesmstone** [ohookins/flickr-shell-uploader#4]
When trying to authenticate I just get redirected to https://flickr.com any ideas why ?

**Comment by ohookins** [comment]
This hasn't been touched in a very long time, it's possible they have changed the authentication mechanism. Do you have any further diagnostic information or is that it?

**Comment by jamesmstone** [comment]
Sorry thats all I have been able to determine.
________________________________

**Comment by jamesmstone** [comment]
Update: Flickr has deprecated non OAuth authentication, this includes `desktop` authentication. Which this library uses. 
Although not quite pure shell, I have made a [`docker image`](https://hub.docker.com/r/jamesmstone/flickr-uploadr/) ([repo](https://github.com/jamesmstone/flickr-uploadr)) that does a similar thing with the new, oauth method of authentication.

**Comment by ohookins** [comment]
This script is so old, and if they have deprecated the authentication flow I'm not too tempted to fix it. There are better solutions out there for sure by now, so I would probably rather put an unrestrictive license on the code and explicitly deprecate it.
